### PR TITLE
Ca 43 santa rosa scraper

### PR DESCRIPTION
**Pull request by naumansharifwork**
Created the Scrape-meta and Scrape for Santa Rosa Police Website

### CODE REVIEW

**Comment by tarakc02** [comment]
The minor changes to the SD and cache code both look unobjectionable to me, but wanted to check with @zstumgoren to make sure those are reasonable changes. I'll begin review of the main santa rosa downloader script...

**Review by zstumgoren — APPROVED** [review]
Changes look good at a glance. Thanks!

**Comment by naumansharifwork** [comment]
hey @tarakc02 this pull request is asking for a approval from maintainers, can you please ask a maintainer to approve thanks. 
Also how can i lint and format with pre-commit.

**Comment by zstumgoren** [comment]
> hey @tarakc02 this pull request is asking for a approval from maintainers, can you please ask a maintainer to approve thanks. Also how can i lint and format with pre-commit.

Hey @naumansharifwork Looks like there's a [minor linting issue](https://github.com/biglocalnews/clean-scraper/actions/runs/10004513463/job/27670469315). Can you try installing `precommit` based on [these docs](https://github.com/biglocalnews/clean-scraper/blob/dev/docs/contributing.md#install-dependencies) and running locally using below steps?

- Navigate to root of repo
- `pipenv run precommit`

 Note that some contributors have had headaches running `precommit` locally -- it can be a pain -- so if you run into issues, ping back and one of us can clone your work and run for you. Thanks!

**Comment by naumansharifwork** [comment]
Hey @zstumgoren i have ran pipenv run pre-commit what should i do next?
Screenshot 2024-07-20 151945

**Comment by zstumgoren** [comment]
Great. Looks like there are no errors from the screenshot. If pre-commit changed any files then commit/push those changes to your branch. That should trigger another run of code checks on GiHub. I can check to see if everything is passing and if so will merge. 

If pre-commit doesn't produce changes, then I would review the errors on GitHub and change them manually on your local fork.

**Comment by naumansharifwork** [comment]
@zstumgoren  i have checked from github logs the linting was failed so i manually checked and fixed those and re-committed, 
also the command to run pre-commit is "pipenv run pre-commit run --all-files" this checks on all files from previous command it was missing files

**Comment by zstumgoren** [comment]
> @zstumgoren i have checked from github logs the linting was failed so i manually checked and fixed those and re-committed, also the command to run pre-commit is "pipenv run pre-commit run --all-files" this checks on all files from previous command it was missing files

Excellent. Thanks for circling back on that! Looks like all checks are passing, so going to merge. Huge thanks for the contribution!

**Pull request merged**
