### PR TITLE
Added The scraper for Humboldt with successful pre-commit run

### PR DESCRIPTION
**Pull request by naumansharifwork**

### CODE REVIEW

**Comment by naumansharifwork** [comment]
Hey @zstumgoren please review this one as well Thanks.

**Comment by zstumgoren** [comment]
@naumansharifwork Checks look good!  I should have asked on the last go-round, but could you post a snippet in this thread showing the directory tree structure produced in the cache directory (e.g. using [tree](https://linux.die.net/man/1/tree) command, along with a small sample of records in the final JSON output from `scrape_meta`? A main goal for us is to retain information about the linkage between assets (videos, audio, pdfs, etc.) and the associated case information, and a visual inspection of the output is one easy way to verify that everything works as expected.

**Comment by naumansharifwork** [comment]
@zstumgoren here is a screenshot of tree
image
image

Also i am uploading meta json
[ca_humboldt_pd.json](https://github.com/user-attachments/files/16365360/ca_humboldt_pd.json)

**Comment by naumansharifwork** [comment]
Hey, @zstumgoren Thanks for the feedback,
For Panel Code:
I was grouping the records in their respective folders for the PDF documents we have a Panel Code e.g 
832.7 (b)(1)(A)(i)
but for the audio/video files we don't have panel code mentioned, They have some case code like this example below but it does not appears to be the date 
image
So i thought it might be panel code as well, i can name them as case id but this case id will not be available for the pdf type of documents,

Parent Page:
i understand about the first part that i should give the cache file location, 
For the download page as the download and the name of document is available on the next page so we are first downloading the download page in cache as well so should i provide its relative path?

File Tree:
For saving the files we are already grouping the documents in their respective penal code 
image
for the audio/video files they are also grouped in their respective case folder e.g
image
All these files will go to the 17-3004 folder,
File names are preserved the same as we get when we download them.
Let me know if we need to change anything in file tree,

**Comment by zstumgoren** [comment]
@naumansharifwork A few follow-ups to your most recent questions:

## Panel Code

In the JSON, does this refer to Penal Code? If so, we should replace with correct spelling -- `penal_code` -- and only fill it out when that information is available. Or you can drop the field, since I'm not certain we'd use that downstream in our processing.

## Parent page vs. download page

> For the download page as the download and the name of document is available on the next page so we are first downloading the download page in cache as well so should i provide its relative path?

Sure, that'd be a good strategy to to handle as:

- `download_page` - relative local path in cache
- `parent_page` - higher-level index page that leads to the `download_page`

## File tree with case-number folders

After reviewing the page a bit more, it appears that the unique "ID" for each case does indeed appear to be case number. These case numbers appear to have a PDF report on the Documents tab, and where available, corresponding audio and video and other assets on the Audio/Video tab.

So the key thing for us would be to use this unique ID to organize the files in separate folders. To expand on my earlier example, for `201504289`, you might have the below structure:

```
ca_humboldt_pd/
ca_humboldt_pd/SB-1421-AB-748-Information.html # parent_page

ca_humboldt_pd/201504289/ # This folder contains case file and related audio/video listed on the "parent_page"
ca_humboldt_pd/201504289/201504289.pdf # NOTE: THIS IS NEW and corresponds to the file on the Documents tab
ca_humboldt_pd/201504289/201504289-085-4 Redacted.wav
```
It sounds like you're already doing this to group audio/video by case, but grouping the police reports (ie the PDFs) under separate penal code folders. Is that correct?

If so, we should get rid of the penal code directories and just save  the case file PDF *inside* the appropriate case folder as illustrated above, using its case number + `.pdf` suffix (or whatever the actual file name of the PDF is based on the URL). That type of structure will greatly help with our downstream processing.

For the penal code, it's fine to add that as a key in the JSON file for each record, where available, and leave blank where it's not available. Or as mentioned above, also fine to drop the field for now. If you decide to keep it in the JSON, we should correct the spelling from `panel_code` to `penal_code`.

**Comment by naumansharifwork** [comment]
[ca_humboldt_pd.json](https://github.com/user-attachments/files/16372871/ca_humboldt_pd.json)
Hey please check json now 
also i am attaching the tree screenshot now
image

**Comment by zstumgoren** [comment]
@naumansharifwork Folder structure looks spot on! Thanks! JSON looks good overall, just one minor note: It appears the `download_page` and `parent_page` are identical:

```json
        "parent_page": "ca_humboldt_pd/SB-1421-AB-748-Information.html",
        "download_page": "ca_humboldt_pd/SB-1421-AB-748-Information.html",
```

If we keep `download_page`, that should be the relative path to a local copy of the HTML from the NextURL page where the file can be dowloaded (i.e. based on the links harvested from the Audio/Video tab).

**Comment by naumansharifwork** [comment]
@zstumgoren download page is same as parent page for the cases where we get the download link actually from the parent page (for document types), EIther we can keep it same or if you want i can remove the download page key for the records where its not required.

**Comment by zstumgoren** [comment]
> @zstumgoren download page is same as parent page for the cases where we get the download link actually from the parent page (for document types), EIther we can keep it same or if you want i can remove the download page key for the records where its not required.

Gotcha. Sure, let's remove it for the cases where `parent_page` and `download_page` are identical. Once that change is done, I think we should be ready to merge. Thanks!

**Comment by naumansharifwork** [comment]
[ca_humboldt_pd.json](https://github.com/user-attachments/files/16416519/ca_humboldt_pd.json)
Hey @zstumgoren done.

**Comment by zstumgoren** [comment]
Looks great! Merging. Huge thanks!

**Review by zstumgoren — APPROVED** [review]

**Pull request merged**
